### ISSUE TITLE
CI: DeadKernelError on CircleCI with wise-allwise-catalog-demo

### ISSUE THREAD

**Issue by bsipocz** [Caltech-IPAC/irsa-tutorials#6]
There is a `DeadKernelError` on circleCI that I cannot reproduce locally. It resolves if I exclude `wise-allwise-catalog-demo` from the execution, however,  building and publishing with GHA works for this notebook. So, it's a little bit a puzzle for now.

Full log is here:
```
# Platform:         linux; (Linux-5.15.0-1057-aws-x86_64-with-glibc2.35)
# Sphinx version:   7.4.7
# Python version:   3.12.4 (CPython)
# Docutils version: 0.21.2
# Jinja2 version:   3.1.4
# Pygments version: 2.18.0

# Last messages:
#   /home/circleci/project/tutorials/irsa-sia-examples/siav2_seip.md: Executing notebook using local CWD [mystnb]
#   /home/circleci/project/tutorials/irsa-sia-examples/siav2_seip.md: Executed notebook in 14.71 seconds [mystnb]
#   reading sources... [ 88%]
#   tutorials/parallelize/Parallelize_Convolution
#   
#   /home/circleci/project/tutorials/parallelize/Parallelize_Convolution.md: Excluded from execution by pattern: 'Parallelize_Convolution.md' [mystnb]
#   reading sources... [100%]
#   tutorials/parquet-catalog-demos/wise-allwise-catalog-demo
#   
#   /home/circleci/project/tutorials/parquet-catalog-demos/wise-allwise-catalog-demo.md: Executing notebook using local CWD [mystnb]

# Loaded extensions:
#   sphinx.ext.mathjax (7.4.7)
#   alabaster (0.7.16)
#   sphinxcontrib.applehelp (1.0.8)
#   sphinxcontrib.devhelp (1.0.6)
#   sphinxcontrib.htmlhelp (2.0.6)
#   sphinxcontrib.serializinghtml (1.1.10)
#   sphinxcontrib.qthelp (1.0.8)
#   myst_nb (1.1.1)
#   sphinx_copybutton (0.5.2)
#   sphinx_book_theme (unknown version)
#   pydata_sphinx_theme (unknown version)

# Traceback:
Traceback (most recent call last):
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/sphinx/application.py", line 378, in build
    self.builder.build_update()
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 318, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 425, in read
    self._read_serial(docnames)
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 477, in _read_serial
    self.read_doc(docname)
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 536, in read_doc
    publisher.publish()
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/sphinx/io.py", line 106, in read
    self.parse()
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/myst_nb/sphinx_.py", line 152, in parse
    with create_client(
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/myst_nb/core/execute/base.py", line 79, in __enter__
    self.start_client()
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/myst_nb/core/execute/direct.py", line 40, in start_client
    result = single_nb_execution(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.4/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/circleci/project/.tox/py312-buildhtml/lib/python3.12/site-packages/nbclient/client.py", line 1009, in async_execute_cell
    raise DeadKernelError("Kernel died") from None
nbclient.exceptions.DeadKernelError: Kernel died


```

**Comment by bsipocz** [comment]
This has been worked around in https://github.com/Caltech-IPAC/irsa-tutorials/pull/5. The notebook is excluded from CircleCI execution during the PR process, but is included in GHA testing and rendering. So I close this issue for now.
